server.port=8081
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#management.endpoint.health.probes.enabled=true
#management.endpoint.show-details=always
#management.endpoints.web.exposure.include=health,info
#management.health.group.readiness.include=db
#management.health.group.liveness.include=ping
#management.info.app.name=mes-service
